// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOlZ0k-0vfjS_kFGPpsA10XhVLK9V8-U8',
    appId: '1:562807053048:web:090b7cc48c38d5098bf90d',
    messagingSenderId: '562807053048',
    projectId: 'seba-732c9',
    authDomain: 'seba-732c9.firebaseapp.com',
    storageBucket: 'seba-732c9.firebasestorage.app',
    measurementId: 'G-76NH1LR8RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlpFDJmLbzWn2h82KqiBjPBHcLICIiE4',
    appId: '1:562807053048:android:735eee29fea2c6cd8bf90d',
    messagingSenderId: '562807053048',
    projectId: 'seba-732c9',
    storageBucket: 'seba-732c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTghjzsjoxuNS0HPBhSdb42_y5bIIjmCc',
    appId: '1:562807053048:ios:54c419ba8ebef8738bf90d',
    messagingSenderId: '562807053048',
    projectId: 'seba-732c9',
    storageBucket: 'seba-732c9.firebasestorage.app',
    iosBundleId: 'com.example.sebaApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTghjzsjoxuNS0HPBhSdb42_y5bIIjmCc',
    appId: '1:562807053048:ios:54c419ba8ebef8738bf90d',
    messagingSenderId: '562807053048',
    projectId: 'seba-732c9',
    storageBucket: 'seba-732c9.firebasestorage.app',
    iosBundleId: 'com.example.sebaApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOlZ0k-0vfjS_kFGPpsA10XhVLK9V8-U8',
    appId: '1:562807053048:web:d2ea401bebb578008bf90d',
    messagingSenderId: '562807053048',
    projectId: 'seba-732c9',
    authDomain: 'seba-732c9.firebaseapp.com',
    storageBucket: 'seba-732c9.firebasestorage.app',
    measurementId: 'G-WGEMGFR847',
  );
}
